#!/bin/bash

# 清理不需要的檔案

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "========================================"
echo "清理不需要的檔案"
echo "========================================"
echo ""
echo "將刪除以下檔案:"
echo ""
echo -e "${YELLOW}🗑️  重複的部署腳本:${NC}"
echo "  - deploy.sh (保留 簡易部署.sh)"
echo "  - deploy-ubuntu.sh (保留 簡易部署.sh)"
echo "  - deploy-micro.sh (保留 簡易部署.sh)"
echo "  - quick-deploy.sh (保留 簡易部署.sh)"
echo "  - quick-fix.sh (保留 一鍵修復.sh)"
echo "  - instant-fix.sh (保留 一鍵修復.sh)"
echo "  - emergency-fix.sh (保留 一鍵修復.sh)"
echo "  - fix-build.sh (功能已整合)"
echo "  - fix-database.sh (功能已整合)"
echo "  - memory-monitor.sh (功能已整合)"
echo "  - 監控腳本.sh (功能已整合)"
echo ""
echo -e "${YELLOW}🗑️  重複的文檔:${NC}"
echo "  - 快速參考.md (保留 README-修復指南.md)"
echo "  - 快速開始.md (保留 README-修復指南.md)"
echo "  - 快速部署.md (保留 README-修復指南.md)"
echo "  - 部署指南.md (保留 README-修復指南.md)"
echo "  - 故障排除.md (保留 修復工具說明.md)"
echo "  - 建置問題解決.md (保留 修復新增學生問題.md)"
echo "  - Ubuntu問題排除.md (保留 Nginx設定指南.md)"
echo "  - 本地建置方案.md (不需要)"
echo "  - 上傳方案.md (保留 upload-fix.bat)"
echo "  - 學生管理新功能測試.md (不需要)"
echo "  - 新功能測試指南.md (不需要)"
echo "  - 測試新功能.md (不需要)"
echo "  - e2-micro優化指南.md (不需要)"
echo "  - Git問題解決.md (不需要)"
echo "  - Windows用戶指南.md (不需要)"
echo ""
echo -e "${YELLOW}🗑️  重複的 Git 工具:${NC}"
echo "  - git-setup.sh (不需要)"
echo "  - git-setup.bat (不需要)"
echo "  - git-status.sh (不需要)"
echo "  - update-github.sh (不需要)"
echo "  - update-github.bat (不需要)"
echo ""
echo -e "${YELLOW}🗑️  其他不需要的檔案:${NC}"
echo "  - diagnose-db.js (功能已整合到 diagnose-api.sh)"
echo "  - init-database.js (後端自動初始化)"
echo ""
echo -e "${GREEN}✅ 保留的重要檔案:${NC}"
echo "  - 簡易部署.sh (主要部署腳本)"
echo "  - 一鍵修復.sh (一鍵修復工具)"
echo "  - setup-nginx.sh (Nginx 配置)"
echo "  - fix-nginx.sh (Nginx 診斷)"
echo "  - update-frontend.sh (前端更新)"
echo "  - diagnose-api.sh (系統診斷)"
echo "  - upload-fix.bat (Windows 上傳)"
echo "  - README-修復指南.md (主要文檔)"
echo "  - Nginx設定指南.md (Nginx 文檔)"
echo "  - Nginx快速參考.md (快速參考)"
echo "  - 修復工具說明.md (工具說明)"
echo "  - 修復新增學生問題.md (問題說明)"
echo "  - 快速修復指南.md (快速指南)"
echo ""
read -p "確認刪除? (y/n): " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "已取消"
    exit 0
fi

echo ""
echo "開始清理..."
echo ""

# 刪除重複的部署腳本
rm -f deploy.sh && echo "✓ 已刪除 deploy.sh"
rm -f deploy-ubuntu.sh && echo "✓ 已刪除 deploy-ubuntu.sh"
rm -f deploy-micro.sh && echo "✓ 已刪除 deploy-micro.sh"
rm -f quick-deploy.sh && echo "✓ 已刪除 quick-deploy.sh"
rm -f quick-fix.sh && echo "✓ 已刪除 quick-fix.sh"
rm -f instant-fix.sh && echo "✓ 已刪除 instant-fix.sh"
rm -f emergency-fix.sh && echo "✓ 已刪除 emergency-fix.sh"
rm -f fix-build.sh && echo "✓ 已刪除 fix-build.sh"
rm -f fix-database.sh && echo "✓ 已刪除 fix-database.sh"
rm -f memory-monitor.sh && echo "✓ 已刪除 memory-monitor.sh"
rm -f 監控腳本.sh && echo "✓ 已刪除 監控腳本.sh"

# 刪除重複的文檔
rm -f 快速參考.md && echo "✓ 已刪除 快速參考.md"
rm -f 快速開始.md && echo "✓ 已刪除 快速開始.md"
rm -f 快速部署.md && echo "✓ 已刪除 快速部署.md"
rm -f 部署指南.md && echo "✓ 已刪除 部署指南.md"
rm -f 故障排除.md && echo "✓ 已刪除 故障排除.md"
rm -f 建置問題解決.md && echo "✓ 已刪除 建置問題解決.md"
rm -f Ubuntu問題排除.md && echo "✓ 已刪除 Ubuntu問題排除.md"
rm -f 本地建置方案.md && echo "✓ 已刪除 本地建置方案.md"
rm -f 上傳方案.md && echo "✓ 已刪除 上傳方案.md"
rm -f 學生管理新功能測試.md && echo "✓ 已刪除 學生管理新功能測試.md"
rm -f 新功能測試指南.md && echo "✓ 已刪除 新功能測試指南.md"
rm -f 測試新功能.md && echo "✓ 已刪除 測試新功能.md"
rm -f e2-micro優化指南.md && echo "✓ 已刪除 e2-micro優化指南.md"
rm -f Git問題解決.md && echo "✓ 已刪除 Git問題解決.md"
rm -f Windows用戶指南.md && echo "✓ 已刪除 Windows用戶指南.md"

# 刪除 Git 工具
rm -f git-setup.sh && echo "✓ 已刪除 git-setup.sh"
rm -f git-setup.bat && echo "✓ 已刪除 git-setup.bat"
rm -f git-status.sh && echo "✓ 已刪除 git-status.sh"
rm -f update-github.sh && echo "✓ 已刪除 update-github.sh"
rm -f update-github.bat && echo "✓ 已刪除 update-github.bat"

# 刪除其他不需要的檔案
rm -f diagnose-db.js && echo "✓ 已刪除 diagnose-db.js"
rm -f init-database.js && echo "✓ 已刪除 init-database.js"

echo ""
echo "========================================"
echo -e "${GREEN}✅ 清理完成！${NC}"
echo "========================================"
echo ""
echo "📁 保留的檔案結構:"
echo ""
echo "📂 部署和修復工具 (7 個)"
echo "  ├─ 簡易部署.sh          - 主要部署腳本"
echo "  ├─ 一鍵修復.sh          - 一鍵修復所有問題"
echo "  ├─ setup-nginx.sh       - Nginx 配置工具"
echo "  ├─ fix-nginx.sh         - Nginx 診斷工具"
echo "  ├─ update-frontend.sh   - 前端更新工具"
echo "  ├─ diagnose-api.sh      - 系統診斷工具"
echo "  └─ upload-fix.bat       - Windows 上傳工具"
echo ""
echo "📂 文檔 (6 個)"
echo "  ├─ README.md                  - 專案說明"
echo "  ├─ README-修復指南.md         - 完整修復指南 ⭐"
echo "  ├─ 快速修復指南.md            - 快速參考卡片"
echo "  ├─ Nginx設定指南.md           - Nginx 詳細說明"
echo "  ├─ Nginx快速參考.md           - Nginx 快速參考"
echo "  ├─ 修復工具說明.md            - 工具使用說明"
echo "  └─ 修復新增學生問題.md        - 問題詳解"
echo ""
echo "📂 配置檔案"
echo "  ├─ package.json"
echo "  ├─ .env"
echo "  ├─ nginx.conf"
echo "  ├─ ecosystem.config.js"
echo "  ├─ docker-compose.yml"
echo "  ├─ Dockerfile.backend"
echo "  └─ Dockerfile.frontend"
echo ""
echo -e "${BLUE}💡 建議: 執行 'git status' 查看變更${NC}"
echo ""
